feat: adding a toggle switch for left panel items
AmruthPillai/Reactive-Resume pull request #462
Opened 2021-02-25 20:46 UTC by anu1097

Description - Saw a good first issue - https://github.com/AmruthPillai/Reactive-Resume/issues/323

Approach taken - Read through the code to understand the data flow. Not the cleanest solution, but does the job.
Thought about creating a generic function or modify safety-check function to avoid code duplication. 
But that would require significant changes hence went against it and used this approach.

2021-03-03 17:32 UTC, anu1097 commented
@AmruthPillai can you have a look. I think its ready to be merged.

2021-03-06 03:10 UTC, AmruthPillai requested changes
This needs to be addressed before we can merge :)

2021-03-06 03:10 UTC, amruthpillai commented on src/contexts/ResumeContext.js
> +            items[index].isVisible = false;
If `isVisible` doesn't exist in the data array, we should have all sections visible by default. Here, when a user tries to import/load an older version of the resume, they wouldn't see any of the sections.

2021-03-06 10:55 UTC, anu1097 commented on src/contexts/ResumeContext.js
> +            items[index].isVisible = false;
```
export const isItemVisible = (section) =>
  section && section.isVisible !== false;
```

I am using this logic to determine whether to display or not. if IsVisible is not present in existing section. This function will return true. So this should handle it.

2021-03-07 03:21 UTC, merged